backend:
  name: git-gateway #test-repo
  branch: main # Branch to update (optional; defaults to master)
local_backend: true # Eliminar para hacer build en prod
# Server local: npx netlify-cms-proxy-server
media_folder: public/img # borrado para probar uploadcare
public_folder: img #borrado para probar uploadcare
media_library:
  name: uploadcare
  config:
    publicKey: fdbe389f8ae715b25611
collections:
  - name: "pages"
    label: "[EN] Pages"
    folder: "content/en"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Contenido"
        name: "content"
        widget: "list"
        label_singular: "bloque"
        types:
          - label: "Bloque de texto"
            name: "textBlock"
            widget: "object"
            fields:
              - {
                  label: "Texto",
                  name: "text",
                  widget: "markdown",
                  buttons: ["bold", "italic", "link"],
                  modes: ["rich_text"],
                  editor_components: [],
                }
          - label: "Bloque de imagen"
            name: "imageBlock"
            widget: "object"
            fields:
              - { label: "Imagen", name: "image", widget: "image" }
              - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de carrusel"
            name: "carouselBlock"
            widget: "object"
            fields:
              - label: "Carrusel"
                name: "carouselList"
                widget: "list"
                label_singular: "Slide"
                fields:
                  - label: "Slide"
                    name: "slide"
                    widget: "object"
                    fields:
                      - { label: "Imagen", name: "image", widget: "image" }
                      - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de título"
            name: "titleBlock"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
          - label: "Bloque de embed Vimeo"
            name: "vimeoBlock"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "string" }
          - label: "Bloque de embed YouTube"
            name: "youtubeBlock"
            widget: "object"
            fields:
              - { label: "URL", name: "url", widget: "string" }
          - label: "Bloque de links"
            name: "linksBlock"
            widget: "object"
            fields:
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                - label: "Link"
                  name: "link"
                  widget: "object"
                  fields:
                    - { label: "Texto", name: "linkText", widget: "string" }
                    - { label: "URL", name: "url", widget: "string" }
  - name: "paginas"
    label: "[ES] Páginas"
    folder: "content/es"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Contenido"
        name: "content"
        widget: "list"
        label_singular: "bloque"
        types:
          - label: "Bloque de texto"
            name: "textBlock"
            widget: "object"
            fields:
              - {
                  label: "Texto",
                  name: "text",
                  widget: "markdown",
                  buttons: ["bold", "italic", "link"],
                  modes: ["rich_text"],
                  editor_components: [],
                }
          - label: "Bloque de imagen"
            name: "imageBlock"
            widget: "object"
            fields:
              - { label: "Imagen", name: "image", widget: "image" }
              - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de carrusel"
            name: "carouselBlock"
            widget: "object"
            fields:
              - label: "Carrusel"
                name: "carouselList"
                widget: "list"
                label_singular: "Slide"
                fields:
                  - label: "Slide"
                    name: "slide"
                    widget: "object"
                    fields:
                      - { label: "Imagen", name: "image", widget: "image" }
                      - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de título"
            name: "titleBlock"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
          - label: "Bloque de embed Vimeo"
            name: "vimeoBlock"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "string" }
          - label: "Bloque de embed YouTube"
            name: "youtubeBlock"
            widget: "object"
            fields:
              - { label: "URL", name: "url", widget: "string" }
          - label: "Bloque de links"
            name: "linksBlock"
            widget: "object"
            fields:
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                - label: "Link"
                  name: "link"
                  widget: "object"
                  fields:
                    - { label: "Texto", name: "linkText", widget: "string" }
                    - { label: "URL", name: "url", widget: "string" }
  - name: "projects"
    label: "[EN] Projects"
    folder: "content/en/projects"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Categoría"
        name: "category"
        widget: "relation"
        collection: "settings"
        file: "categories"
        value_field: "categoriesList.*.category.titleEN"
        search_fields: ["categoriesList.*.category.titleEN"]
        multiple: true
      - label: "Ficha técnica"
        name: "specs"
        widget: "list"
        field: { label: "Elemento", name: "spec", widget: "string" }
      - label: "Créditos"
        name: "credits"
        widget: "list"
        fields:
          - label: "Crédito"
            name: "credit"
            widget: "object"
            fields:
              - { label: "Persona", name: "person", widget: "string" }
              - { label: "Rol", name: "role", widget: "string" }
      - label: "Contenido"
        name: "content"
        widget: "list"
        label_singular: "bloque"
        types:
          - label: "Bloque de texto"
            name: "textBlock"
            widget: "object"
            fields:
              - {
                  label: "Texto",
                  name: "text",
                  widget: "markdown",
                  buttons: ["bold", "italic", "link"],
                  modes: ["rich_text"],
                  editor_components: [],
                }
          - label: "Bloque de imagen"
            name: "imageBlock"
            widget: "object"
            fields:
              - { label: "Imagen", name: "image", widget: "image" }
              - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de carrusel"
            name: "carouselBlock"
            widget: "object"
            fields:
              - label: "Carrusel"
                name: "carouselList"
                widget: "list"
                label_singular: "Slide"
                fields:
                  - label: "Slide"
                    name: "slide"
                    widget: "object"
                    fields:
                      - { label: "Imagen", name: "image", widget: "image" }
                      - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de título"
            name: "titleBlock"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
          - label: "Bloque de embed Vimeo"
            name: "vimeoBlock"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "string" }
          - label: "Bloque de links"
            name: "linksBlock"
            widget: "object"
            fields:
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                - label: "Link"
                  name: "link"
                  widget: "object"
                  fields:
                    - { label: "Texto", name: "linkText", widget: "string" }
                    - { label: "URL", name: "url", widget: "string" }
  - name: "proyectos"
    label: "[ES] Proyectos"
    folder: "content/es/projects"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Categoría"
        name: "category"
        widget: "relation"
        collection: "settings"
        file: "categories"
        value_field: "categoriesList.*.category.titleES"
        search_fields: ["categoriesList.*.category.titleES"]
        multiple: true
      - label: "Ficha técnica"
        name: "specs"
        widget: "list"
        field: { label: "Elemento", name: "spec", widget: "string" }
      - label: "Créditos"
        name: "credits"
        widget: "list"
        fields:
          - label: "Crédito"
            name: "credit"
            widget: "object"
            fields:
              - { label: "Persona", name: "person", widget: "string" }
              - { label: "Rol", name: "role", widget: "string" }
      - label: "Contenido"
        name: "content"
        label_singular: "bloque"
        widget: "list"
        types:
          - label: "Bloque de texto"
            name: "textBlock"
            widget: "object"
            fields:
              - {
                  label: "Texto",
                  name: "text",
                  widget: "markdown",
                  buttons: ["bold", "italic", "link"],
                  modes: ["rich_text"],
                  editor_components: [],
                }
          - label: "Bloque de imagen"
            name: "imageBlock"
            widget: "object"
            fields:
              - { label: "Imagen", name: "image", widget: "image" }
              - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de carrusel"
            name: "carouselBlock"
            widget: "object"
            fields:
              - label: "Carrusel"
                name: "carouselList"
                widget: "list"
                label_singular: "Slide"
                fields:
                  - label: "Slide"
                    name: "slide"
                    widget: "object"
                    fields:
                      - { label: "Imagen", name: "image", widget: "image" }
                      - { label: "Epígrafe", name: "caption", widget: "string", required: false }
          - label: "Bloque de título"
            name: "titleBlock"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
          - label: "Bloque de embed Vimeo"
            name: "vimeoBlock"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "string" }
          - label: "Bloque de links"
            name: "linksBlock"
            widget: "object"
            fields:
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                - label: "Link"
                  name: "link"
                  widget: "object"
                  fields:
                    - { label: "Texto", name: "linkText", widget: "string" }
                    - { label: "URL", name: "url", widget: "string" }
  - name: "settings"
    label: "Configuración"
    files:
      - label: "Contenido general"
        name: "generalContent"
        file: "settings/general-content.md"
        fields:
          - { label: "Meta description (EN)", name: "metaDescriptionEN", widget: "text" }
          - { label: "Meta description (ES)", name: "metaDescriptionES", widget: "text" }
          - { label: "Video de portada", name: "coverVideo", widget: "string" }
          - { label: "Pie de página", name: "pageFooter", widget: "string" }
          - label: "Orden de proyectos EN"
            name: "projectOrderEN"
            widget: "relation"
            collection: "projects"
            value_field: "title"
            search_fields: ["title"]
            multiple: true
          - label: "Orden de proyectos ES"
            name: "projectOrderES"
            widget: "relation"
            collection: "proyectos"
            value_field: "title"
            search_fields: ["title"]
            multiple: true
      - label: "Categorías"
        name: "categories"
        file: "settings/categories.md"
        fields:
          - label: "Listado de categorías"
            name: "categoriesList"
            widget: "list"
            label_singular: "Categoría"
            fields:
              - label: "Categoría"
                name: "category"
                widget: "object"
                fields:
                  - { label: "Título ES", name: "titleES", widget: "string" }
                  - { label: "Título EN", name: "titleEN", widget: "string" }
                  - {
                      label: "Color",
                      name: "color",
                      widget: "color",
                      default: "#FFFFFF",
                    }
                  - { label: "url", name: "URL", widget: "string" }